version: 'build-{build}-{branch}'

os: unstable
image: Visual Studio 2017   # на этом VM-образе установлены все Visual Studio с 2008 по 2015

branches:
  only:
    - master
    
init:
    # секция инициализации, исполняется до клонирования проекта
    # скорее всего, строчка ниже необязательна (так должно быть по умолчанию),
    # вместе с тем, она присутствует в официальных примерах, так что пусть будет:
    - git config --global core.autocrlf input
clone_folder: c:\src # выбираем локальную директорию для клонирования
shallow_clone: true              # копируем только последний коммит, без истории (git clone --depth 1)

matrix:
    fast_finish: true           # останавливаемся после возникновения ошибки в каком-то из заданий

platform:
    # будем гонять CI на amd64 и x86...
    - x64    
    - x86

configuration:
    - Release

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3
    
environment:
    CODECOV_TOKEN:
        secure: e8qe5I3ngSiMDPZsLfLBP7iCZJHrFD8gsXAYTkfQ1HL09UBk10s4vWNEDVMnFoM8
    BUILD_CONFIG: $(configuration)
    COVERALLS_REPO_TOKEN:
        secure: /W0ImKAfLG96HA1nlkhhW0ntoJCRq7wps5
    APPVEYOR_RDP_PASSWORD: 1234as!&
    matrix:
        - TOOLCHAIN: msvc15
install:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
before_build:
    - nuget restore c:\src\TcpCommunication.sln
  
build_script:
    - msbuild c:\src\TcpCommunication.sln /m /property:Configuration=Release /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" > build.log
    - type build.log

on_failure:
    - type build.log
on_finish:
    #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
    - path: ./x64/Release/
      name: artifacts